# Generated by Django 5.0.7 on 2024-12-19 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PumpFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pumps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pumps images')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('feed', models.PositiveIntegerField()),
                ('pressure', models.FloatField()),
                ('cavitation', models.FloatField()),
                ('rotation_speed', models.PositiveIntegerField()),
                ('power', models.FloatField()),
                ('mass', models.FloatField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pump_selection.pumpfamily')),
            ],
        ),
    ]
