# Generated by Django 5.0.7 on 2024-12-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pump_selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumps',
            name='mass_all',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pumps',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pumps',
            name='feed',
            field=models.FloatField(),
        ),
    ]
