# Generated by Django 5.0.7 on 2024-12-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pump_selection', '0002_pumps_mass_all_alter_pumps_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumps',
            name='a0',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pumps',
            name='b0',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pumps',
            name='c0',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
