from django.shortcuts import render
from django.http import HttpResponse
from django.http import FileResponse
from django.shortcuts import redirect
import math
import cadquery as cq
from cadquery import exporters
import numpy as np
import os
from pathlib import Path
import plotly.graph_objects as go
import zipfile
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def wheel_calc(request):
    context = {
        'selects': [
            {'type': 'option', 'placeholder': '–†–∞—Å—á–µ—Ç —Ä–∞–±–æ—á–µ–≥–æ –∫–æ–ª–µ—Å–∞:',
             'keys': ['–¶–µ–Ω—Ç—Ä–æ–±–µ–∂–Ω—ã–π –Ω–∞—Å–æ—Å', '–°—Ç—Ä—É–π–Ω—ã–π –Ω–∞—Å–æ—Å']},
            {'type': 'input', 'placeholder': '–†–∞—Å—Ö–æ–¥, –º¬≥/—á', 'name': 'flow_rate', 'value': ''},
            {'type': 'input', 'placeholder': '–ù–∞–ø–æ—Ä, –º', 'name': 'pressure', 'value': ''},
            {'type': 'input', 'placeholder': '–ü–ª–æ—Ç–Ω–æ—Å—Ç—å, –∫–≥/–º¬≥', 'name': 'density', 'value': ''},
            {'type': 'input', 'placeholder': '–ß–∞—Å—Ç–æ—Ç–∞ –≤—Ä., –æ–±/–º–∏–Ω', 'name': 'rotation_speed', 'value': ''},
            {'type': 'float', 'placeholder': '–í—è–∑–∫–æ—Å—Ç—å, –º–º¬≤/—Å', 'name': 'viscosity', 'value': ''},
        ],
        'calculations': [
            {'name': '–ö–æ—ç—Ñ—Ñ–∏—Ü–∏–µ–Ω—Ç –±—ã—Å—Ç—Ä–æ—Ö–æ–¥–Ω–æ—Å—Ç–∏ –Ω–∞—Å–æ—Å–∞: ', 'value': None, 'round': 0, 'unit': '', },
            {'name': '–ù–∞—Ä—É–∂–Ω—ã–π –¥–∏–∞–º–µ—Ç—Ä —Ä–∞–±–æ—á–µ–≥–æ –∫–æ–ª–µ—Å–∞: ', 'value': None, 'round': 4, 'unit': ' –º–º', },
            {'name': '–®–∏—Ä–∏–Ω–∞ –ª–æ–ø–∞—Å—Ç–Ω–æ–≥–æ –∫–∞–Ω–∞–ª–∞ —Ä–∞–±–æ—á–µ–≥–æ –∫–æ–ª–µ—Å–∞ –Ω–∞ –≤—Ö–æ–¥–µ: ', 'value': None, 'round': 4,
             'unit': ' –º–º', },
            {'name': '–ü—Ä–∏–≤–µ–¥–µ–Ω–Ω—ã–π –¥–∏–∞–º–µ—Ç—Ä –≤—Ö–æ–¥–∞ –≤ —Ä–∞–±–æ—á–µ–µ –∫–æ–ª–µ—Å–æ 1: ', 'value': None, 'round': 4,
             'unit': ' –º–º', },
            {'name': '–ü—Ä–∏–≤–µ–¥–µ–Ω–Ω—ã–π –¥–∏–∞–º–µ—Ç—Ä –≤—Ö–æ–¥–∞ –≤ —Ä–∞–±–æ—á–µ–µ –∫–æ–ª–µ—Å–æ 2: ', 'value': None, 'round': 4,
             'unit': ' –º–º', },
            {'name': '–û–±—ä–µ–º–Ω—ã–π –ö–ü–î: ', 'value': None, 'round': 3, 'unit': ' %', },
            {'name': '–ì–∏–¥—Ä–∞–≤–ª–∏—á–µ—Å–∫–∏–π –ö–ü–î: ', 'value': None, 'round': 3, 'unit': ' %', },
            {'name': '–í–Ω—É—Ç—Ä. –º–µ—Ö. –ö–ü–î: ', 'value': None, 'round': 3, 'unit': ' %', },
            {'name': '–ü–æ–ª–Ω—ã–π –æ–∂–∏–¥–∞–µ–º—ã–π –ö–ü–î: ', 'value': None, 'round': 3, 'unit': ' %', },
            {'name': '–ú–æ—â–Ω–æ—Å—Ç—å: ', 'value': None, 'round': 0, 'unit': ' –∫–í—Ç', },
            {'name': '–ú–æ—â–Ω–æ—Å—Ç—å –º–∞–∫—Å–∏–º–∞–ª—å–Ω–∞—è: ', 'value': None, 'round': 0, 'unit': ' –∫–í—Ç', },
            {'name': '–î–∏–∞–º–µ—Ç—Ä –≤–∞–ª–∞: ', 'value': None, 'round': 0, 'unit': ' –º–º', },
            {'name': '–î–∏–∞–º–µ—Ç—Ä –≤—Ö–æ–¥–∞ –≤ —Ä–∞–±–æ—á–µ–µ –∫–æ–ª–µ—Å–æ: ', 'value': None, 'round': 4, 'unit': ' –º–º', },
        ],
        'error': None,
        'plots': [],
        'input_data': {},
        'pause_calculations': False

    }

    if request.method == "POST":
        if 'calculate_params' in request.POST:
            context['pause_calculations'] = True
        else:
            context['pause_calculations'] = False
        # –ü–æ–ª—É—á–∞–µ–º –¥–∞–Ω–Ω—ã–µ –∏–∑ —Ñ–æ—Ä–º—ã
        try:
            flow_rate = float(request.POST.get("flow_rate"))
            pressure = float(request.POST.get("pressure"))
            density = float(request.POST.get("density"))
            rotation_speed = float(request.POST.get("rotation_speed"))
            viscosity = float(request.POST.get("viscosity").replace(',', '.'))
            for select in context['selects']:
                if select['type'] != 'option':
                    name = select['name']
                    value = request.POST.get(name, "")
                    if select['type'] == 'float':
                        value = value.replace(',', '.')
                    select['value'] = value
            if context['pause_calculations']:
                calculated_values = calculations(flow_rate, pressure, density, rotation_speed)  # –ü–æ–ª—É—á–∞–µ–º —Ä–∞—Å—á—ë—Ç—ã
                update_context(context, calculated_values)  # –û–±–Ω–æ–≤–ª—è–µ–º context
                format_context_list(context)  # —Ñ–æ—Ä–º–∞—Ç–∏—Ä–æ–≤–∞–Ω–∏–µ —Ç–µ–∫—Å—Ç–∞

                r_list, angle_total_list, number_of_blades, thickness, b_list_updated = calculations_2(flow_rate, pressure, density, rotation_speed)
                contour_1, contour_2, contour_3, heihgt_blades = create_section_meridional(flow_rate, pressure, density, rotation_speed, r_list, b_list_updated)
                create_wheel(flow_rate, pressure, density, rotation_speed, contour_1, contour_2, contour_3, heihgt_blades, r_list, angle_total_list, number_of_blades,
                             thickness)

            # find_valid_combinations()
            if 'download_model' in request.POST:
                response = handle_download_model(request, context)
                if response:
                    return response
        except ZeroDivisionError:
            context['error'] = '–û—à–∏–±–∫–∞: –¥–µ–ª–µ–Ω–∏–µ –Ω–∞ –Ω–æ–ª—å. –ë—ã–ª–∏ –≤—ã–±—Ä–∞–Ω—ã –Ω–µ–ø—Ä–∞–≤–∏–ª—å–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ.'
        except ValueError:
            context['error'] = '–û—à–∏–±–∫–∞: –≤–≤–µ–¥–µ–Ω—ã –Ω–µ–∫–æ—Ä—Ä–µ–∫—Ç–Ω—ã–µ —á–∏—Å–ª–æ–≤—ã–µ –¥–∞–Ω–Ω—ã–µ.'
        except TypeError as e:
            if "complex" in str(e):
                context['error'] = '–û—à–∏–±–∫–∞: —Ä–∞—Å—á—ë—Ç—ã –ø—Ä–∏–≤–µ–ª–∏ –∫ –∫–æ–º–ø–ª–µ–∫—Å–Ω–æ–º—É —á–∏—Å–ª—É, –∞ –æ–∂–∏–¥–∞–ª–æ—Å—å –≤–µ—â–µ—Å—Ç–≤–µ–Ω–Ω–æ–µ.'
            else:
                context['error'] = f'–û—à–∏–±–∫–∞ —Ç–∏–ø–∞ –¥–∞–Ω–Ω—ã—Ö: {str(e)}'
    else:
        # –î–ª—è GET-–∑–∞–ø—Ä–æ—Å–∞ –æ—à–∏–±–∫–∞ –≤—Å–µ–≥–¥–∞ None ‚Äî —ç—Ç–æ —Å–±—Ä–∞—Å—ã–≤–∞–µ—Ç —Å—Ç–∞—Ä—ã–µ –æ—à–∏–±–∫–∏
        context['error'] = None
    print("Request method:", request.method)
    print("Error in context:", context.get('error'))
    return render(request, 'calculations.html', context)


def calculations(flow_rate, pressure, density, rotation_speed):
    # –ö–æ—ç—Ñ—Ñ–∏—Ü–∏–µ–Ω—Ç –±—ã—Å—Ç—Ä–æ—Ö–æ–¥–Ω–æ—Å—Ç–∏ –Ω–∞—Å–æ—Å–∞
    pump_speed_coef = round((3.65 * rotation_speed * math.sqrt(flow_rate / 60 / 60)) / (pressure ** (3 / 4)))
    # –ù–∞—Ä—É–∂–Ω—ã–π –¥–∏–∞–º–µ—Ç—Ä —Ä–∞–±–æ—á–µ–≥–æ –∫–æ–ª–µ—Å–∞
    k_od = 9.35 * math.sqrt(100 / pump_speed_coef)
    outer_diam_of_work_wheel = round((k_od * (flow_rate / 3600 / rotation_speed) ** (1 / 3)), 4) * 1000
    # –®–∏—Ä–∏–Ω–∞ –ª–æ–ø–∞—Å—Ç–Ω–æ–≥–æ –∫–∞–Ω–∞–ª–∞ —Ä–∞–±–æ—á–µ–≥–æ –∫–æ–ª–µ—Å–∞ –Ω–∞ –≤—Ö–æ–¥–µ
    if pump_speed_coef <= 200:
        k_w = 0.8 * math.sqrt(pump_speed_coef / 100)
    else:
        k_w = 0.635 * (pump_speed_coef / 100) ** (5 / 6)
    width_in_enter_of_work_wheel = round(k_w * (flow_rate / 3600 / rotation_speed) ** (1 / 3), 4)
    # –ü—Ä–∏–≤–µ–¥–µ–Ω–Ω—ã–π –¥–∏–∞–º–µ—Ç—Ä –≤—Ö–æ–¥–∞ –≤ —Ä–∞–±–æ—á–µ–µ –∫–æ–ª–µ—Å–æ
    k_in = 4.5
    inner_diam_of_work_wheel_1 = round(k_in * (flow_rate / 60 / rotation_speed) ** (2 / 3), 4)
    number_of_blade = 7
    alpha = 0.1
    v_0 = alpha * (flow_rate / 3600 * rotation_speed ** 2) ** (1 / 3)
    inner_diam_of_work_wheel_2 = round((4 * flow_rate / 3600 / (math.pi * v_0)) ** (1 / 2), 4)
    # –ü—Ä–µ–¥–≤–∞—Ä–∏—Ç–µ–ª—å–Ω–∞—è –æ—Ü–µ–Ω–∫–∞ –ö–ü–î
    n_0 = (1 + (0.68 / (pump_speed_coef ** (2 / 3)))) ** (-1) * 100
    if inner_diam_of_work_wheel_1 < inner_diam_of_work_wheel_2:
        n_r = (1 - (0.42 / (math.log10(inner_diam_of_work_wheel_1 * 1000) - 0.172) ** 2)) * 100
    else:
        n_r = (1 - (0.42 / (math.log10(inner_diam_of_work_wheel_2 * 1000) - 0.172) ** 2)) * 100
    n_m = (1 + (28.6 / pump_speed_coef) ** 2) ** (-1) * 100
    n_a = n_0 / 100 * n_r / 100 * n_m / 100 * 100
    # –ú–∞–∫—Å–∏–º–∞–ª—å–Ω–∞—è –º–æ—â–Ω–æ—Å—Ç—å –Ω–∞—Å–æ—Å–∞
    power = density * 9.81 * pressure * flow_rate / 60 / 60 / (n_a / 100) / 1000
    k_n = 1.1
    power_max = power * k_n
    # –û–ø—Ä–µ–¥–µ–ª–µ–Ω–∏–µ —Ä–∞–∑–º–µ—Ä–æ–≤ –≤–∞–ª–∞ –∏ –≤—Ç—É–ª–∫–∏ (—Å—Ç—É–ø–∏—Ü—ã) –∫–æ–ª–µ—Å–∞
    m_max = round(power_max * 30 * 1000 / (math.pi * rotation_speed), 3)
    tau = 600 * 10 ** 5
    shaft_diameter = math.ceil(((m_max / (0.2 * tau)) ** (1 / 3) * 1000) / 10) * 10
    # –û–ø—Ä–µ–¥–µ–ª–µ–Ω–∏–µ –¥–∏–∞–º–µ—Ç—Ä–∞ –≤—Ö–æ–¥–Ω–æ–π —Ä–∞–±–æ—á–µ–≥–æ –∫–æ–ª–µ—Å–∞ –∏ –¥–∏–∞–º–µ—Ç—Ä–∞ –≤—Ö–æ–¥–∞ –≤ —Ä–∞–±–æ—á–µ–µ –∫–æ–ª–µ—Å–æ
    k_inner = 1.3
    hub_diameter = math.ceil(shaft_diameter * k_inner / 5) * 5
    if pump_speed_coef <= 90:
        k_inner_0 = 1.1
    elif 90 < pump_speed_coef <= 300:
        k_inner_0 = 0.8
    else:
        k_inner_0 = 0.7
    if inner_diam_of_work_wheel_1 < inner_diam_of_work_wheel_2:
        enter_diameter_0 = round(((inner_diam_of_work_wheel_1 * 1000) ** 2 + (shaft_diameter * k_inner) ** 2) ** 0.5, 1)
    else:
        enter_diameter_0 = round(((inner_diam_of_work_wheel_2 * 1000) ** 2 + (shaft_diameter * k_inner) ** 2) ** 0.5, 1)
    enter_diameter_1 = enter_diameter_0 * k_inner_0

    return (pump_speed_coef, outer_diam_of_work_wheel, width_in_enter_of_work_wheel, inner_diam_of_work_wheel_1,
            inner_diam_of_work_wheel_2, n_0, n_r, n_m, n_a, power, power_max, shaft_diameter, enter_diameter_0,
            enter_diameter_1, hub_diameter, v_0)


def calculations_2(flow_rate, pressure, density, rotation_speed, num_items=10):
    data = calculations(flow_rate, pressure, density, rotation_speed)
    print(data[0])

    n_vol = round(data[5] / 100, 3)
    n_hydro = round(data[6] / 100, 3)
    d_hub = data[14]  # d–≤—Ç –≤ –º–º

    if 50 <= data[0] <= 60:
        number_of_blade = 9 if data[0] < 55 else 8
    elif 60 < data[0] <= 180:
        number_of_blade = 8 if data[0] < 120 else 6
    elif 180 < data[0] <= 350:
        number_of_blade = 6
    elif 350 < data[0] <= 600:
        number_of_blade = 6 if data[0] < 475 else 5
    else:
        raise ValueError("–£–¥–µ–ª—å–Ω–∞—è —Å–∫–æ—Ä–æ—Å—Ç—å ns –≤–Ω–µ –¥–∏–∞–ø–∞–∑–æ–Ω–∞ (50‚Ä¶600)")

    flow_rate_m_s = flow_rate / 3600
    r_outer = data[1] / 2
    r_inner = data[13] / 2
    v_t_1 = (4 * flow_rate_m_s) / (n_vol * math.pi * (math.pow(2 * r_inner / 1000, 2) - math.pow(d_hub / 1000, 2)))
    u_2 = math.pi * (2 * r_outer / 1000) * rotation_speed / 60
    m = round(r_outer / r_inner)

    def linear_interpolate_or_extrapolate(x, x_table, y_table):
        return round(float(np.interp(x, x_table, y_table, left=None, right=None)), 1)

    d2 = data[1]

    d2_table = [100, 200, 300, 500, 800]
    delta_1_table = [1.25, 1.25, 2.0, 3.5, 4.5]
    delta_2_table = [3.0, 3.75, 4.5, 5.5, 9.0]
    delta_max_table = [4.0, 4.5, 6.5, 7.5, 12.0]

    thickness_of_blade_inlet = linear_interpolate_or_extrapolate(d2, d2_table, delta_1_table)
    thickness_of_blade_outlet = linear_interpolate_or_extrapolate(d2, d2_table, delta_2_table)
    thickness_of_blade_max = linear_interpolate_or_extrapolate(d2, d2_table, delta_max_table)

    if data[0] < 50:
        angle_b_l_2_range = (20, 25)
    elif 50 <= data[0] <= 100:
        angle_b_l_2_range = (25, 35)
    elif 100 < data[0] <= 200:
        angle_b_l_2_range = (23, 27)
    elif 200 < data[0] <= 400:
        angle_b_l_2_range = (18, 22)
    else:
        angle_b_l_2_range = (15, 18)

    angle_b_l_1_range = (15, 30)
    attack_angle_b_range = (3, 8)

    v_t_0 = data[15]
    b_1 = flow_rate_m_s / (n_vol * math.pi * (2 * r_inner / 1000) * v_t_1)
    u_1 = math.pi * (2 * r_inner / 1000) * rotation_speed / 60
    angle_b_1 = round(math.atan(v_t_1 / u_1) * 180 / math.pi)

    found = False

    for angle in range(max(angle_b_l_2_range), min(angle_b_l_2_range) - 1, -1):
        for attack_angle in range(min(attack_angle_b_range), max(attack_angle_b_range) + 1):
            angle_b_l_1 = angle_b_1 + attack_angle
            if not (min(angle_b_l_1_range) <= angle_b_l_1 <= max(angle_b_l_1_range)):
                continue

            flow_resistance_koef_1 = 1 - (number_of_blade * thickness_of_blade_inlet /
                                          (math.pi * 2 * r_inner * math.sin(angle_b_l_1 * math.pi / 180)))
            v_t_2 = v_t_1 / flow_resistance_koef_1

            flow_resistance_koef_2 = 1 - (number_of_blade * thickness_of_blade_outlet /
                                          (math.pi * 2 * r_outer * math.sin(angle * math.pi / 180)))

            v_t_3 = flow_rate_m_s / (flow_resistance_koef_2 * math.pi * 2 * r_outer / 1000 * data[2])
            v_t_4 = v_t_3 * flow_resistance_koef_2

            angle_b_2 = angle - attack_angle

            if data[0] < 150:
                fi = 0.6 + 0.6 * math.sin(angle_b_2 * math.pi / 180)
            elif 150 <= data[0] <= 200:
                fi = (1.6 * math.sin(angle_b_2 * math.pi / 180) +
                      math.sin(angle_b_1 * math.pi / 180) * (r_inner / r_outer) ** 2)
            else:
                fi = (math.sin(angle_b_1 * math.pi / 180) *
                      (1.7 + 13.3 * ((v_t_4 / (u_2 * math.tan(angle_b_2 * math.pi / 180))) ** 2)))

            mu = (1 + ((2 * fi * (2 * r_outer / 1000)) /
                       (number_of_blade * ((2 * r_outer / 1000) ** 2 - (2 * r_inner / 1000) ** 2)))) ** -1

            v_u_2_inf = 9.81 * pressure / (mu * n_hydro * u_2)
            pressure_inf = v_u_2_inf * u_2 / 9.81
            pressure_check = pressure_inf * mu * n_hydro

            cot_b_l_1 = (u_2 - v_u_2_inf) / v_t_4

            number_of_blade_checked = round(6.5 * ((m + 1) / (m - 1)) *
                                            math.sin((angle_b_l_1 + angle) * math.pi / 2 / 180))

            angle_b_l_2_checked = (
                    2 * math.asin((number_of_blade_checked * (m - 1)) / (6.5 * (m + 1))) * 180 / math.pi - angle_b_l_1)

            v_dependence_k = (v_t_4 - v_t_1) / ((r_outer - r_inner) / 1000)
            v_dependence_b = v_t_4 - v_dependence_k * r_outer / 1000

            if abs(angle - angle_b_l_2_checked) < 0.5:
                angle_b_l_2 = angle_b_l_2_checked
                found = True

                # print(f"–ù–∞–π–¥–µ–Ω–æ —Ä–µ—à–µ–Ω–∏–µ:")
                # print(f"d_2 = {round(d2, 1)}")
                # print(f"d_hub = {d_hub}")
                # print(f"angle_b_l_1 = {round(angle_b_l_1, 1)}")
                # print(f"angle_b_l_2 = {round(angle_b_l_2, 1)}")
                # print(f"attack_angle = {attack_angle}")
                # print(f"number_of_blade_checked = {number_of_blade_checked}")
                break
        if found:
            break

    # üîê –ù–æ–≤–∞—è –∑–∞—â–∏—Ç–∞ –æ—Ç –Ω–µ–æ–ø—Ä–µ–¥–µ–ª—ë–Ω–Ω—ã—Ö –ø–µ—Ä–µ–º–µ–Ω–Ω—ã—Ö:
    if not found:
        raise ValueError("–ù–µ —É–¥–∞–ª–æ—Å—å –Ω–∞–π—Ç–∏ –ø–æ–¥—Ö–æ–¥—è—â–∏–µ —É–≥–ª—ã. –ü–æ–¥–±–µ—Ä–∏—Ç–µ –¥—Ä—É–≥–∏–µ –ø–∞—Ä–∞–º–µ—Ç—Ä—ã –∏–ª–∏ –ø—Ä–æ–≤–µ—Ä—å—Ç–µ –≤—Ö–æ–¥–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ.")

    # –î–∞–ª—å–Ω–µ–π—à–∏–µ –≤—ã—á–∏—Å–ª–µ–Ω–∏—è...
    r_step = (r_outer - r_inner) / num_items
    r_list = [r_inner]
    for i in range(num_items):
        r_list.append(r_list[i] + r_step)

    v_list = []
    for i in range(len(r_list)):
        v_list.append(v_dependence_k * r_list[i] / 1000 + v_dependence_b)

    flow_rate_real = flow_rate / 3600 / n_vol
    b_list = []
    for i in range(len(r_list)):
        b_list.append(round((flow_rate_real / (2 * math.pi * r_list[i] / 1000 * v_list[i])), 4))

    b_list_updated = []
    for i in b_list:
        if i > b_list[-1]:
            b_list_updated.append(i)
        else:
            b_list_updated.append(data[2])

    w = ((thickness_of_blade_inlet - thickness_of_blade_max) * (r_inner / 1000 - r_outer / 1000) /
         (thickness_of_blade_inlet - thickness_of_blade_outlet))
    f = 2 * w - 2 * r_inner / 1000
    t = - r_inner / 1000 * w - r_outer / 1000 * w + (r_inner / 1000) ** 2
    temporary_1 = (- f + math.sqrt(f ** 2 - 4 * t)) / 2
    temporary_2 = (- f - math.sqrt(f ** 2 - 4 * t)) / 2

    thickness_dependence_c = thickness_of_blade_max
    if temporary_1 > r_outer / 1000:
        thickness_dependence_b = temporary_2
    else:
        thickness_dependence_b = temporary_1
    thickness_dependence_a = ((thickness_of_blade_inlet - thickness_of_blade_max) /
                              (2 * (((r_inner / 1000) - (r_outer / 1000)) *
                                    ((r_inner / 1000) + (r_outer / 1000) - 2 * thickness_dependence_b))))

    thickness_list = []
    for i in r_list:
        thickness_list.append(
            round((thickness_dependence_a * ((i / 1000) - thickness_dependence_b) ** 2 + thickness_dependence_c), 1))

    w_inlet = v_list[0] / math.sin(angle_b_l_1 * math.pi / 180)
    w_outlet = v_list[-1] / math.sin(angle_b_l_2 * math.pi / 180)
    w_dependence_k = (w_outlet - w_inlet) / (r_outer / 1000 - r_inner / 1000)
    w_dependence_b = w_outlet - w_dependence_k * r_outer / 1000
    w_list = [w_inlet]
    for i in range(num_items):
        w_list.append(w_dependence_k * r_list[i + 1] / 1000 + w_dependence_b)

    b_l_list = []
    for i in range(len(r_list)):
        b_l_list.append(round((math.asin(v_list[i] / w_list[i] + number_of_blade_checked * thickness_list[i] /
                                         (2 * math.pi * r_list[i])) * 180 / math.pi), 1))

    num_integrate_list = []
    for i in range(len(r_list)):
        num_integrate_list.append(1 / (r_list[i] * math.tan(b_l_list[i] * math.pi / 180) / 1000))

    angle_step_list = []
    for i in range(num_items):
        angle_step_list.append(round((((r_step / 1000) * (num_integrate_list[i] +
                                                          num_integrate_list[i + 1]) / 2) * 180 / math.pi), 1))

    angle_total_list = []
    cumulative = 0
    for i in angle_step_list:
        cumulative += i
        angle_total_list.append(round(cumulative, 1))

    return r_list, angle_total_list, number_of_blade_checked, thickness_list, b_list_updated


def create_section_meridional(flow_rate, pressure, density, rotation_speed, r_list, b_list_updated, debug_mode=True):
    data = calculations(flow_rate, pressure, density, rotation_speed)

    r_list_mm = [round(i, 2) for i in r_list]
    b_list_updated_mm = [round(i * 1000, 2) for i in b_list_updated]

    hub_radius = round(data[14] / 2, 2)
    shaft_radius = data[11] / 2
    thickness = round(b_list_updated_mm[-1] / 3, 0)

    points = [
        (0, r_list_mm[-1]),  # –¢–æ—á–∫–∞ 1
        (0, hub_radius + data[12] / 2),  # –¢–æ—á–∫–∞ 2
        (-data[12] / 2, hub_radius),  # –¢–æ—á–∫–∞ 3
        (-data[12] / 2, shaft_radius),  # –¢–æ—á–∫–∞ 4
        (thickness, shaft_radius),  # –¢–æ—á–∫–∞ 5
        (thickness, r_list_mm[-1])  # –¢–æ—á–∫–∞ 6
    ]

    b_list_updated_mm_reversed = b_list_updated_mm[::-1]

    r_list_mm_reversed = r_list_mm[::-1]

    point_center = (-data[12] / 2, hub_radius + data[12] / 2)

    points_2 = []
    points_3 = []

    for i, j in zip(r_list_mm_reversed, b_list_updated_mm_reversed):
        if i > point_center[1]:
            points_2.append((-j / 2, i))
            points_3.append((-j, i))
        else:
            points_2.append(
                (
                    point_center[0] + math.sqrt((abs(point_center[0]) - j / 2) ** 2 - (i - point_center[1]) ** 2),
                    i
                )
            )
            points_3.append(
                (
                    j * (-math.sqrt((abs(point_center[0]) - j / 2) ** 2 - (i - point_center[1]) ** 2)) /
                    (2 * (abs(point_center[0]) - j / 2)) + point_center[0] + math.sqrt(
                        (abs(point_center[0]) - j / 2) ** 2 - (i - point_center[1]) ** 2),
                    j * (point_center[1] - i) / (2 * (abs(point_center[0]) - j / 2)) + i
                )
            )

    points_3.append((point_center[0], r_list_mm[0]))

    # –î–æ–±–∞–≤–ª—è–µ–º –ø—Ä–æ–º–µ–∂—É—Ç–æ—á–Ω—ã–µ —Ç–æ—á–∫–∏ –º–µ–∂–¥—É –ø–æ—Å–ª–µ–¥–Ω–∏–º–∏ –¥–≤—É–º—è —Å –∫–æ–Ω—Ç—Ä–æ–ª–µ–º –∫—Ä–∏–≤–∏–∑–Ω—ã
    if len(points_3) >= 2:
        # –ë–µ—Ä–µ–º –ø–æ—Å–ª–µ–¥–Ω–∏–µ –¥–≤–µ —Ç–æ—á–∫–∏
        p_start = points_3[-2]
        p_end = points_3[-1]

        # –ü–∞—Ä–∞–º–µ—Ç—Ä—ã –¥–ª—è —Ä–µ–≥—É–ª–∏—Ä–æ–≤–∫–∏ –∫—Ä–∏–≤–∏–∑–Ω—ã
        NUM_POINTS = 5  # –ö–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø—Ä–æ–º–µ–∂—É—Ç–æ—á–Ω—ã—Ö —Ç–æ—á–µ–∫
        CURVATURE = 0.1  # 0.0 - –ª–∏–Ω–µ–π–Ω–æ, >0 - –≤—ã–ø—É–∫–ª–æ—Å—Ç—å –≤–≤–µ—Ä—Ö

        # –í—ã—á–∏—Å–ª—è–µ–º –∫–æ–Ω—Ç—Ä–æ–ª—å–Ω—É—é —Ç–æ—á–∫—É –¥–ª—è –∫—Ä–∏–≤–∏–∑–Ω—ã
        control_y = min(p_start[1], p_end[1]) - abs(p_start[1] - p_end[1]) * CURVATURE

        # –ö–≤–∞–¥—Ä–∞—Ç–∏—á–Ω–∞—è –∏–Ω—Ç–µ—Ä–ø–æ–ª—è—Ü–∏—è
        x_values = np.linspace(p_start[0], p_end[0], NUM_POINTS + 2)[1:-1]
        y_values = []

        for x in x_values:
            t = (x - p_start[0]) / (p_end[0] - p_start[0])
            y = (1 - t) ** 2 * p_start[1] + 2 * (1 - t) * t * control_y + t ** 2 * p_end[1]
            y_values.append(y)

        # –î–æ–±–∞–≤–ª—è–µ–º –Ω–æ–≤—ã–µ —Ç–æ—á–∫–∏
        new_points = list(zip(x_values, y_values))
        points_3 = points_3[:-1] + new_points + [points_3[-1]]

    # –°–æ–∑–¥–∞–µ–º —Å–ø–ª–∞–π–Ω —Å –ø—Ä–∏–Ω—É–¥–∏—Ç–µ–ª—å–Ω—ã–º –æ–≥—Ä–∞–Ω–∏—á–µ–Ω–∏–µ–º
    spline_points = []
    for i in range(len(points_3) - 1):
        # –õ–∏–Ω–µ–π–Ω–∞—è –∏–Ω—Ç–µ—Ä–ø–æ–ª—è—Ü–∏—è —Å –∫–æ—Ä—Ä–µ–∫—Ü–∏–µ–π –∫—Ä–∏–≤–∏–∑–Ω—ã
        spline_points.extend([
            cq.Vector(points_3[i][0], points_3[i][1], 0),
            cq.Vector(
                (points_3[i][0] + points_3[i + 1][0]) / 2,
                max((points_3[i][1] + points_3[i + 1][1]) / 2, min(points_3[i][1], points_3[i + 1][1]))
            )
        ])
    spline_points.append(cq.Vector(points_3[-1][0], points_3[-1][1], 0))

    mid_point = []

    # –°–Ω–∞—á–∞–ª–∞ –Ω–∞–π–¥–µ–º, —Å–∫–æ–ª—å–∫–æ –ø–æ–¥—Ä—è–¥ –æ–¥–∏–Ω–∞–∫–æ–≤—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π –≤ –Ω–∞—á–∞–ª–µ —Å–ø–∏—Å–∫–∞
    same_value_count = 1
    for idx in range(1, len(b_list_updated_mm_reversed)):
        if b_list_updated_mm_reversed[idx] == b_list_updated_mm_reversed[0]:
            same_value_count += 1
        else:
            break

    # –ï—Å–ª–∏ –æ–¥–∏–Ω–∞–∫–æ–≤—ã—Ö –ø–æ–¥—Ä—è–¥ 4 –∏–ª–∏ –±–æ–ª—å—à–µ, –±–µ—Ä—ë–º 4-—é
    if same_value_count >= 4:
        target_idx = 3  # 4-–π –ø–æ –ø–æ—Ä—è–¥–∫—É (—Å –∏–Ω–¥–µ–∫—Å–æ–º 3)
    else:
        # –ò–Ω–∞—á–µ –±–µ—Ä—ë–º –ø–æ—Å–ª–µ–¥–Ω—é—é –∏–∑ –æ–¥–∏–Ω–∞–∫–æ–≤—ã—Ö
        target_idx = same_value_count - 1

    current_j = b_list_updated_mm_reversed[target_idx]
    current_i = r_list_mm_reversed[target_idx]
    mid_point.append((-current_j - thickness, current_i))

    mid_point = tuple(mid_point)

    temp_center = [(
        (-spline_points[-1].x ** 2 + mid_point[0][0] ** 2 - (spline_points[-1].y + thickness - mid_point[0][1]) ** 2) /
        (2 * (-spline_points[-1].x + mid_point[0][0])),
        mid_point[0][1]
    )]
    temp_center = tuple(temp_center)

    r_1 = abs(temp_center[0][0] - mid_point[0][0])
    x_1 = (spline_points[-1].x - mid_point[0][0]) / 2 + mid_point[0][0]
    y_1 = temp_center[0][1] - math.sqrt(r_1 ** 2 - (x_1 - temp_center[0][0]) ** 2)

    height = abs(spline_points[-1].x + 1)

    result = (cq.Workplane("XY")
              .moveTo(points[0][0], points[0][1])
              .lineTo(points[1][0], points[1][1])
              .threePointArc(
        (
            (points[1][0] + points[2][0]) / 2,
            points[1][1] + math.cos(math.pi / 6) * points[2][0]
        ),
        (points[2][0], points[2][1])
    )
              .lineTo(points[3][0], points[3][1])
              .lineTo(points[4][0], points[4][1])
              .lineTo(points[5][0], points[5][1])
              .close()  # –ó–∞–º—ã–∫–∞–Ω–∏–µ –∫–æ–Ω—Ç—É—Ä–∞
              )

    result_1 = (cq.Workplane("XY")
                .moveTo(points_3[0][0], points_3[0][1])
                .spline(spline_points)
                .lineTo(spline_points[-1].x, spline_points[-1].y + thickness)
                .threePointArc(
        (x_1, y_1),
        (mid_point[0][0], mid_point[0][1]))
                .lineTo(spline_points[0].x - thickness, spline_points[0].y)
                .close()
                )

    result_2 = (cq.Workplane("XY")
                .moveTo(spline_points[-1].x, spline_points[-1].y + thickness)
                .threePointArc(
        (x_1, y_1),
        (mid_point[0][0], mid_point[0][1]))
                .lineTo(spline_points[0].x - thickness, spline_points[0].y)
                .lineTo(spline_points[-1].x, spline_points[0].y)
                .close()
                )

    if debug_mode:
        # –≠–∫—Å–ø–æ—Ä—Ç –æ—Å–Ω–æ–≤–Ω–æ–≥–æ –∫–æ–Ω—Ç—É—Ä–∞
        main_wp = cq.Workplane("XY").add(result.val())
        cq.exporters.export(main_wp, 'debug_main_contour.step', 'STEP')

        # –≠–∫—Å–ø–æ—Ä—Ç –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ–≥–æ –∫–æ–Ω—Ç—É—Ä–∞
        additional_wp = cq.Workplane("XY").add(result_1.val())
        cq.exporters.export(additional_wp, 'debug_additional_contour.step', 'STEP')

    return result, result_1, result_2, height


def create_wheel(flow_rate, pressure, density, rotation_speed, contour1, contour2, contour3, height, r_list, angle_total_list, number_of_blades, thickness):
    """–°–æ–∑–¥–∞–µ—Ç –∫–æ–ª–µ—Å–æ –∏–∑ –≤—Ä–∞—â–µ–Ω–Ω—ã—Ö –∫–æ–Ω—Ç—É—Ä–æ–≤ –∏ –≤—ã–¥–∞–≤–ª–∏–≤–∞–µ—Ç –ª–æ–ø–∞—Ç–∫–∏"""
    data = calculations(flow_rate, pressure, density, rotation_speed)
    d_2 = data[1]
    try:
        # 1. –°–æ–∑–¥–∞–µ–º –æ—Å–Ω–æ–≤–Ω–æ–µ —Ç–µ–ª–æ –∏–∑ –∫–æ–Ω—Ç—É—Ä–æ–≤
        main_body = (
            contour1.revolve(360, (0, 0, 0), (1, 0, 0))
            .union(contour2.revolve(360, (0, 0, 0), (1, 0, 0)))
        )

        # 2. –°–æ–∑–¥–∞–µ–º –ª–æ–ø–∞—Ç–∫–∏
        blades_data = create_section_blades(
            r_list,
            angle_total_list,
            number_of_blades,
            thickness,
            debug=False
        )

        if not blades_data or 'faces' not in blades_data:
            raise ValueError("–û—à–∏–±–∫–∞ —Å–æ–∑–¥–∞–Ω–∏—è –ª–æ–ø–∞—Ç–æ–∫")

        # 3. –°–æ–∑–¥–∞–µ–º –∏ –≤—ã–¥–∞–≤–ª–∏–≤–∞–µ–º –ª–æ–ø–∞—Ç–∫–∏
        extruded_blades = cq.Workplane("ZY")
        for face in blades_data['faces']:
            extruded_blades = extruded_blades.add(face).extrude(height)

        # 4. –û–±—ä–µ–¥–∏–Ω—è–µ–º –≤—Å–µ –∫–æ–º–ø–æ–Ω–µ–Ω—Ç—ã
        final_body = main_body.union(extruded_blades).cut(contour3.revolve(360, (0, 0, 0), (1, 0, 0)))

        # 6. –í—ã—Ä–µ–∑–∞–µ–º –∫–æ–ª—å—Ü–æ –Ω–∞ –∫—Ä–∞–π–Ω–µ–π –ª–µ–≤–æ–π —Å—Ç–æ—Ä–æ–Ω–µ (X-)
        ring_inner_radius = max(r_list)  # –≤–Ω—É—Ç—Ä–µ–Ω–Ω–∏–π —Ä–∞–¥–∏—É—Å –∫–æ–ª—å—Ü–∞
        ring_outer_radius = ring_inner_radius + 30  # –≤–Ω–µ—à–Ω–∏–π —Ä–∞–¥–∏—É—Å –∫–æ–ª—å—Ü–∞
        # –ü–æ–ª—É—á–∞–µ–º –≥–∞–±–∞—Ä–∏—Ç—ã —Ç–µ–ª–∞
        bbox = final_body.val().BoundingBox()
        x_min = bbox.xmin - 0.1  # –Ω–µ–±–æ–ª—å—à–æ–µ —Å–º–µ—â–µ–Ω–∏–µ –≤ -X
        x_max = bbox.xmax

        ring_thickness = (x_max - x_min) + 10  # –≥–ª—É–±–∏–Ω–∞ —Å –∑–∞–ø–∞—Å–æ–º
        ring_cut = (
            cq.Workplane("YZ").workplane(offset=x_min)
            .circle(ring_outer_radius)
            .circle(ring_inner_radius)
            .extrude(ring_thickness)
        )

        final_body = final_body.cut(ring_cut)

        d_str = f"{d_2:.1f}".replace('.', '_')  # –æ–∫—Ä—É–≥–ª—è–µ–º –¥–æ 1 –∑–Ω–∞–∫–∞ –∏ –∑–∞–º–µ–Ω—è–µ–º —Ç–æ—á–∫—É
        file_name = f"Wheel_{d_str}.step"

        # 5. –≠–∫—Å–ø–æ—Ä—Ç
        cq.exporters.export(final_body, file_name, 'STEP')

        return final_body

    except Exception as e:
        print(f"–û—à–∏–±–∫–∞ —Å–æ–∑–¥–∞–Ω–∏—è –∫–æ–ª–µ—Å–∞: {str(e)}")
        return None


def rotate_vector(v, angle_deg, axis='x'):
    """–í—Ä–∞—â–µ–Ω–∏–µ –≤–µ–∫—Ç–æ—Ä–∞ –≤–æ–∫—Ä—É–≥ –≤—ã–±—Ä–∞–Ω–Ω–æ–π –æ—Å–∏"""
    angle = math.radians(angle_deg)
    x, y, z = v.x, v.y, v.z

    if axis.lower() == 'x':
        return cq.Vector(
            x,
            y * math.cos(angle) - z * math.sin(angle),
            y * math.sin(angle) + z * math.cos(angle)
        )
    elif axis.lower() == 'z':
        return cq.Vector(
            x * math.cos(angle) - y * math.sin(angle),
            x * math.sin(angle) + y * math.cos(angle),
            z
        )
    else:
        raise ValueError("–ù–µ–ø–æ–¥–¥–µ—Ä–∂–∏–≤–∞–µ–º–∞—è –æ—Å—å –≤—Ä–∞—â–µ–Ω–∏—è")


def create_section_blades(r_list, angle_total_list, number_of_blades, thickness, debug=True):
    # –ì–µ–Ω–µ—Ä–∞—Ü–∏—è –±–∞–∑–æ–≤–æ–≥–æ –ø—Ä–æ—Ñ–∏–ª—è –≤ –ø–ª–æ—Å–∫–æ—Å—Ç–∏ ZY
    points = [cq.Vector(0, r_list[0], 0)]  # (Z, Y, X)

    for i, angle in enumerate(angle_total_list):
        r = r_list[i + 1]
        rad_angle = math.radians(angle)
        # –ü—Ä–µ–æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏–µ –≤ –ø–ª–æ—Å–∫–æ—Å—Ç—å ZY: (Z, Y, X)
        points.append(cq.Vector(
            0,
            r * math.cos(rad_angle),
            r * math.sin(rad_angle)
        ))

    all_wire_list = []

    for blade_idx in range(number_of_blades):
        # –ü–æ–≤–æ—Ä–æ—Ç –≤–æ–∫—Ä—É–≥ –æ—Å–∏ X –¥–ª—è –ø–ª–æ—Å–∫–æ—Å—Ç–∏ ZY
        angle = blade_idx * (360 / number_of_blades)
        rotated_points = [rotate_vector(p, angle, axis='x') for p in points]

        # –ì–µ–Ω–µ—Ä–∞—Ü–∏—è –∫–æ–Ω—Ç—É—Ä–æ–≤ —Å —Ç–æ–ª—â–∏–Ω–æ–π
        outer_points = []
        inner_points = []

        for i, p in enumerate(rotated_points):
            # –í—ã—á–∏—Å–ª–µ–Ω–∏–µ –Ω–æ—Ä–º–∞–ª–∏ –≤ –ø–ª–æ—Å–∫–æ—Å—Ç–∏ ZY
            if i == 0:
                tangent = rotated_points[i + 1] - p
            elif i == len(rotated_points) - 1:
                tangent = p - rotated_points[i - 1]
            else:
                tangent = rotated_points[i + 1] - rotated_points[i - 1]

            # –ù–æ—Ä–º–∞–ª—å –∫ –∫–∞—Å–∞—Ç–µ–ª—å–Ω–æ–π –≤ –ø–ª–æ—Å–∫–æ—Å—Ç–∏ ZY
            normal = tangent.cross(cq.Vector(1, 0, 0)).normalized()  # –û—Å—å X –ø–µ—Ä–ø–µ–Ω–¥–∏–∫—É–ª—è—Ä–Ω–∞ –ø–ª–æ—Å–∫–æ—Å—Ç–∏ ZY
            offset = normal * thickness[i] / 2

            outer_points.append(p + offset)
            inner_points.append(p - offset)

        # –°–æ–∑–¥–∞–Ω–∏–µ –∑–∞–º–∫–Ω—É—Ç–æ–≥–æ –∫–æ–Ω—Ç—É—Ä–∞
        edges = [
            cq.Edge.makeSpline(outer_points),
            cq.Edge.makeLine(outer_points[-1], inner_points[-1]),
            cq.Edge.makeSpline(list(reversed(inner_points))),
            cq.Edge.makeLine(inner_points[0], outer_points[0])
        ]

        try:
            wire = cq.Wire.assembleEdges(edges)
            all_wire_list.append(wire)

            # –≠–∫—Å–ø–æ—Ä—Ç –¥–ª—è –¥–µ–±–∞–≥–∞
            if debug:
                cq.exporters.export(wire, f'debug_blade_{blade_idx}.step')
        except Exception as e:
            print(f"–û—à–∏–±–∫–∞ —Å–æ–∑–¥–∞–Ω–∏—è –ø—Ä–æ–≤–æ–ª–æ—á–Ω–æ–≥–æ –∫–æ–Ω—Ç—É—Ä–∞ –¥–ª—è –ª–æ–ø–∞—Å—Ç–∏ {blade_idx}: {e}")

    # –°–æ–∑–¥–∞–Ω–∏–µ –æ–±—â–µ–≥–æ Compound
    compound = cq.Compound.makeCompound(all_wire_list)

    # –≠–∫—Å–ø–æ—Ä—Ç –æ–±—â–µ–≥–æ —Ñ–∞–π–ª–∞
    if debug:
        cq.exporters.export(compound, 'all_blades_compound.step')

    # –°–æ–∑–¥–∞–Ω–∏–µ –≥—Ä–∞–Ω–µ–π
    faces = []
    for wire in all_wire_list:
        try:
            faces.append(cq.Face.makeFromWires(wire))
        except Exception as e:
            print(f"–û—à–∏–±–∫–∞ —Å–æ–∑–¥–∞–Ω–∏—è –≥—Ä–∞–Ω–∏: {e}")

    return {
        'wires': all_wire_list,
        'faces': faces,
        'compound': compound
    }


def update_context(context, values):
    for calculation, value in zip(context['calculations'], values):
        calculation['value'] = value


def format_context_list(data_list):
    for item in data_list['calculations']:
        if item['value'] is not None:
            if item['value'] < 1:
                item['value'] = round(item['value'], item['round'])
            else:
                item['value'] = int(item['value'])

    return data_list


def find_valid_combinations():
    from collections import defaultdict

    valid_combinations = []
    grouped_results = defaultdict(lambda: {
        "pressures": [],
        "densities": [],
        "rotation_speeds": []
    })
    index = 1
    total = 0

    for flow_rate in range(100, 1001, 10):  # –ü–æ–¥–∞—á–∞, –º¬≥/—á
        for pressure in range(50, 501, 10):  # –ù–∞–ø–æ—Ä, –º
            for density in range(900, 1101, 50):  # –ü–ª–æ—Ç–Ω–æ—Å—Ç—å, –∫–≥/–º¬≥
                for rotation_speed in range(1000, 3001, 50):  # –ß–∞—Å—Ç–æ—Ç–∞ –≤—Ä–∞—â–µ–Ω–∏—è, –æ–±/–º–∏–Ω
                    total += 1
                    try:
                        pump_speed_coef, *_ = calculations(flow_rate, pressure, density, rotation_speed)
                        if 50 <= pump_speed_coef <= 600:
                            valid_combinations.append({
                                "‚Ññ": index,
                                "flow_rate": flow_rate,
                                "pressure": pressure,
                                "density": density,
                                "rotation_speed": rotation_speed
                            })
                            index += 1

                            # –ì—Ä—É–ø–ø–∏—Ä–æ–≤–∫–∞ –ø–æ –¥–∏–∞–ø–∞–∑–æ–Ω–∞–º –ø–æ–¥–∞—á–∏ (–Ω–∞–ø—Ä–∏–º–µ—Ä, 100-199, 200-299 –∏ —Ç.–¥.)
                            range_start = (flow_rate // 100) * 100
                            range_key = f"{range_start}-{range_start + 99}"
                            grouped_results[range_key]["pressures"].append(pressure)
                            grouped_results[range_key]["densities"].append(density)
                            grouped_results[range_key]["rotation_speeds"].append(rotation_speed)
                    except Exception:
                        continue

    print(f"\n‚úÖ –ù–∞–π–¥–µ–Ω–æ –¥–æ–ø—É—Å—Ç–∏–º—ã—Ö –∫–æ–º–±–∏–Ω–∞—Ü–∏–π: {len(valid_combinations)} –∏–∑ {total}\n")

    for flow_range, params in grouped_results.items():
        p_min, p_max = min(params["pressures"]), max(params["pressures"])
        d_min, d_max = min(params["densities"]), max(params["densities"])
        r_min, r_max = min(params["rotation_speeds"]), max(params["rotation_speeds"])
        print(f"–î–ª—è –ø–æ–¥–∞—á–∏ {flow_range} –º¬≥/—á:")
        print(f"  –ù–∞–ø–æ—Ä: –æ—Ç {p_min} –¥–æ {p_max} –º")
        print(f"  –ü–ª–æ—Ç–Ω–æ—Å—Ç—å: –æ—Ç {d_min} –¥–æ {d_max} –∫–≥/–º¬≥")
        print(f"  –ß–∞—Å—Ç–æ—Ç–∞ –≤—Ä–∞—â–µ–Ω–∏—è: –æ—Ç {r_min} –¥–æ {r_max} –æ–±/–º–∏–Ω\n")

    return valid_combinations


def handle_download_model(request, context):
    # ... –ø–æ–ª—É—á–∞–µ–º –ø–∞—Ä–∞–º–µ—Ç—Ä—ã ...
    # –ü–∞—Ä–∞–º–µ—Ç—Ä—ã –ø–µ—Ä–µ–¥–∞—é—Ç—Å—è –∏–ª–∏ —Å–æ–∑–¥–∞—é—Ç—Å—è:
    flow_rate = float(request.POST.get("flow_rate"))
    pressure = float(request.POST.get("pressure"))
    density = float(request.POST.get("density"))
    rotation_speed = float(request.POST.get("rotation_speed"))
    r_list, angle_total_list, number_of_blades, thickness, b_list_updated = calculations_2(flow_rate, pressure, density, rotation_speed)
    contour_1, contour_2, contour_3, heihgt_blades = create_section_meridional(flow_rate, pressure, density, rotation_speed, r_list, b_list_updated)
    data = calculations(flow_rate, pressure, density, rotation_speed)
    d_2 = data[1]

    if not all([contour_1, contour_2, contour_3, heihgt_blades, r_list, angle_total_list, number_of_blades, thickness, b_list_updated]):
        raise ValueError("–ù–µ –≤—Å–µ –≥–µ–æ–º–µ—Ç—Ä–∏—á–µ—Å–∫–∏–µ –ø–∞—Ä–∞–º–µ—Ç—Ä—ã –∑–∞–¥–∞–Ω—ã")

    # –°–æ–∑–¥–∞—ë–º –º–æ–¥–µ–ª—å –∏ —ç–∫—Å–ø–æ—Ä—Ç–∏—Ä—É–µ–º
    final_body = create_wheel(flow_rate, pressure, density, rotation_speed, contour_1, contour_2, contour_3, heihgt_blades, r_list, angle_total_list, number_of_blades,
                              thickness)

    if final_body is None:
        raise ValueError("–ú–æ–¥–µ–ª—å –Ω–µ –±—ã–ª–∞ —Å–æ–∑–¥–∞–Ω–∞")

    # –ò–º—è —Ñ–∞–π–ª–∞
    d_str = f"{d_2:.1f}".replace('.', '_')
    filename = f"Wheel_{d_str}.step"

    # –ü—Ä–æ–≤–µ—Ä—è–µ–º, —á—Ç–æ —Ñ–∞–π–ª —Å—É—â–µ—Å—Ç–≤—É–µ—Ç
    if not os.path.exists(filename):
        raise FileNotFoundError(f"–§–∞–π–ª {filename} –Ω–µ –Ω–∞–π–¥–µ–Ω")

    # –í–æ–∑–≤—Ä–∞—â–∞–µ–º –∫–∞–∫ –∑–∞–≥—Ä—É–∑–∫—É
    return FileResponse(open(filename, 'rb'), as_attachment=True, filename=filename)

# def handle_download_model(request, context):
#     try:
#         flow_rate = float(request.POST.get("flow_rate", "").replace(',', '.'))
#         pressure = float(request.POST.get("pressure", "").replace(',', '.'))
#         density = float(request.POST.get("density", "").replace(',', '.'))
#         rotation_speed = float(request.POST.get("rotation_speed", "").replace(',', '.'))
#
#         # –ó–¥–µ—Å—å –ø–æ–ª—É—á–∏ –∏–ª–∏ —Å–≥–µ–Ω–µ—Ä–∏—Ä—É–π –∫–æ–Ω—Ç—É—Ä—ã, —Å–ø–∏—Å–∫–∏ –∏ –ø–∞—Ä–∞–º–µ—Ç—Ä—ã
#         contour1 = context.get('contour1')  # –Ω–∞–ø—Ä–∏–º–µ—Ä, —Å–æ—Ö—Ä–∞–Ω–µ–Ω–æ —Ä–∞–Ω–µ–µ
#         contour2 = context.get('contour2')
#         contour3 = context.get('contour3')
#         r_list = context.get('r_list')
#         angle_total_list = context.get('angle_total_list')
#         number_of_blades = context.get('number_of_blades')
#         thickness = context.get('blade_thickness')
#         height = context.get('blade_height')
#
#         if not all([contour1, contour2, contour3, r_list, angle_total_list, number_of_blades, thickness, height]):
#             raise ValueError("–ù–µ –≤—Å–µ –≥–µ–æ–º–µ—Ç—Ä–∏—á–µ—Å–∫–∏–µ –ø–∞—Ä–∞–º–µ—Ç—Ä—ã –∑–∞–¥–∞–Ω—ã")
#
#         context['logs'].append("–ù–∞—á–∏–Ω–∞–µ–º —Å–æ–∑–¥–∞–Ω–∏–µ –º–æ–¥–µ–ª–∏ —Ä–∞–±–æ—á–µ–≥–æ –∫–æ–ª–µ—Å–∞...")
#         wheel = create_wheel(
#             flow_rate, pressure, density, rotation_speed,
#             contour1, contour2, contour3,
#             height, r_list, angle_total_list,
#             number_of_blades, thickness
#         )
#
#         if not wheel:
#             raise RuntimeError("–ù–µ —É–¥–∞–ª–æ—Å—å —Å–æ–∑–¥–∞—Ç—å —Ä–∞–±–æ—á–µ–µ –∫–æ–ª–µ—Å–æ")
#
#         # –î–æ–±–∞–≤–ª—è–µ–º –∏–º—è —Ñ–∞–π–ª–∞
#         d_str = f"{wheel.val().BoundingBox().zlen:.1f}".replace('.', '_')  # –∏–ª–∏ –¥—Ä—É–≥–æ–µ –∏–º—è
#         file_name = f"Wheel_{d_str}.step"
#
#         files_to_zip = [file_name, 'screw_lead.step', 'screw_driven.step', 'stator.step', 'pump_assembly.step']
#
#         # –ü—Ä–æ–≤–µ—Ä–∫–∞ —Å—É—â–µ—Å—Ç–≤–æ–≤–∞–Ω–∏—è
#         if not all(os.path.exists(file) for file in files_to_zip):
#             raise FileNotFoundError("–ù–µ–∫–æ—Ç–æ—Ä—ã–µ —Ñ–∞–π–ª—ã –º–æ–¥–µ–ª–µ–π –Ω–µ –Ω–∞–π–¥–µ–Ω—ã")
#
#         zip_filename = 'screw_models.zip'
#         with zipfile.ZipFile(zip_filename, 'w') as zipf:
#             for file in files_to_zip:
#                 zipf.write(file, arcname=os.path.basename(file))
#
#         with open(zip_filename, 'rb') as f:
#             response = HttpResponse(f.read(), content_type='application/zip')
#             response['Content-Disposition'] = f'attachment; filename="{zip_filename}"'
#             return response
#
#     except Exception as e:
#         context['error'] = f"–û—à–∏–±–∫–∞ –ø—Ä–∏ —Å–æ–∑–¥–∞–Ω–∏–∏ –º–æ–¥–µ–ª–∏: {e}"
#         logger.error(f"–û—à–∏–±–∫–∞ –ø—Ä–∏ —ç–∫—Å–ø–æ—Ä—Ç–µ –º–æ–¥–µ–ª–∏: {e}", exc_info=True)
#         return None
